## Submitted by Bhargavi Duggirala, UID: 005634488

### Part 1: Understanding the data

#### a)

In [1]:
import pandas as pd
import numpy as np

In [2]:
sushi_utilities = pd.read_csv('sushi_utilities_mat.csv', header=None)
sushi_description = pd.read_csv('sushi_descriptions.csv', header=None)
sushi_desc = np.array(sushi_description.iloc[:,1])

In [3]:
sushi_utilities.head(5)

0         1         2         3         4         5         6   \
0  2.587382  1.735096  2.805784  2.808497  2.051500  2.530000  2.262429   
1  1.729766  1.470804  1.468309  1.378944  0.833270  1.100750  0.577461   
2  3.344767  3.302255  3.846140  3.076611  3.027984  2.617583  3.186150   
3  3.382407  3.338540  3.465177  2.537292  3.679260  2.213637  3.441076   
4  2.774192  1.930653  2.026012  2.033315  1.617532  1.870940  2.167780   

         7         8         9   ...        90        91        92        93  \
0  2.189008  2.512121  2.695214  ...  1.584592  2.261775  1.384078  1.302735   
1  1.241744  0.782385  1.782568  ...  0.592737  1.086077 -0.257822 -0.403802   
2  2.706815  3.890304  3.457028  ...  1.659859  2.554965  1.323442  1.366464   
3  2.650789  4.027575  3.485529  ...  2.374736  2.673804  1.914855  2.090422   
4  1.810621  1.830054  2.701257  ...  1.281234  1.609595  1.244307  1.348403   

         94        95        96        97        98        99  
0  1.617816  2.145763  2.030173  1.361016  1.624062  1.548308  
1  0.581268  1.015560  0.851418  0.275960  0.420321  0.308964  
2  1.681589  1.964062  2.242885  1.439764  1.685639  1.734439  
3  2.389358  2.538216  2.459458  2.323644  2.076592  2.329594  
4  1.132644  1.507787  1.473952  1.081278  1.163032  1.054110  

[5 rows x 100 columns]

In [4]:
sushi_utilities = np.asarray(sushi_utilities)

In [5]:
out_arr = np.argsort(sushi_utilities[0,:])

In [6]:
sorted_array = sushi_desc[out_arr]

In [7]:
print(f'Five most preferred sushis for customer 1 are: {np.flip(sorted_array[-5:])}')

Five most preferred sushis for customer 1 are: ['negi_toro (fatty flesh of tuna minced to a paste and mixed with chopped green leaves of Welsh onions)'
 'ika (squid)' 'maguro (tuna)' 'samon (salmon)'
 'inari (fried tofu wrapper)']


#### b)

In [8]:
out_arr_2 = np.argsort(sushi_utilities[1,:])

In [9]:
sorted_array_2 = sushi_desc[out_arr_2]

In [10]:
print(f'Five least preferred sushis for customer 2 are: {sorted_array_2[0:5]}')

Five least preferred sushis for customer 2 are: ['karasumi (dried mullet roe)' 'komochi_konbu (herring roe & sea tangle)'
 'kyabia (caviar)' 'awabi (abalone)' 'kazunoko (herring roe)']


#### c)

In [11]:
sorted_ranks = np.arange(100)

In [12]:
sorted_ranks.reshape(1,100)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [13]:
#getting the corresponding sushi names
for i in range(sushi_utilities.shape[0]):
    out_arr = np.argsort(sushi_utilities[i,:])
    out_arr = np.argsort(out_arr)
    sorted_ranks = np.vstack([sorted_ranks, out_arr])
   

In [14]:
sorted_ranks.shape

(501, 100)

In [15]:
sorted_ranks = pd.DataFrame(sorted_ranks)
sorted_ranks = sorted_ranks.iloc[1:,:]

In [16]:
### Ranked DataFRame in descending order
sorted_ranks.head(5)

0   1   2   3   4   5   6   7   8   9   ...  90  91  92  93  94  95  96  \
1  89  44  97  98  61  87  74  71  85  91  ...  28  73   6   3  31  69  58   
2  97  93  92  87  52  76  41  83  49  99  ...  44  73   2   0  42  67  55   
3  89  87  96  84  82  72  85  73  98  92  ...  14  65   2   4  15  38  54   
4  88  87  90  44  97  17  89  52  99  92  ...  31  54   3  13  33  45  37   
5  98  78  83  84  50  73  90  65  67  97  ...  21  48  18  29   5  39  37   

   97  98  99  
1   4  32  24  
2  22  32  25  
3   7  16  19  
4  27  12  28  
5   2   7   1  

[5 rows x 100 columns]

In [17]:
mean_array = np.mean(sorted_ranks, axis=0)

In [18]:
mean_DataFrame = pd.DataFrame(mean_array)
final_df = pd.concat([mean_DataFrame, sushi_description.iloc[:,1]], axis=1)

In [19]:
final_df.columns=['mean','desc']

In [20]:
sorted_final_df = final_df.sort_values(by=['mean'], ascending = False).reset_index(drop=True)

In [21]:
print(f'Rank of each of the 100 sushis according to their utilities (from best to worst):\n{sorted_final_df.iloc[:,1]}')

Rank of each of the 100 sushis according to their utilities (from best to worst):
0     negi_toro (fatty flesh of tuna minced to a pas...
1                                         maguro (tuna)
2                                     kurumaebi (prawn)
3                  negi_toro_maki (roll style of no.37)
4                                          ebi (shrimp)
                            ...                        
95                                namako (sea cucumber)
96                                        okura (gumbo)
97                          karasumi (dried mullet roe)
98         himo_kyu_maki (part of clam & cucumber roll)
99                                      kyabia (caviar)
Name: desc, Length: 100, dtype: object


In [22]:
print(f'Best ranked Sushis:\n{sorted_final_df.iloc[0:5,1]}')

Best ranked Sushis:
0    negi_toro (fatty flesh of tuna minced to a pas...
1                                        maguro (tuna)
2                                    kurumaebi (prawn)
3                 negi_toro_maki (roll style of no.37)
4                                         ebi (shrimp)
Name: desc, dtype: object


#### d)

In [23]:
print(f'Sushi with the worst average rank in the 500 customers: {sorted_final_df.iloc[-1,1]}')

Sushi with the worst average rank in the 500 customers: kyabia (caviar)


#### e)

In [24]:
std_array = np.std(sorted_ranks, axis=0)

In [25]:
std_DataFrame = pd.DataFrame(std_array)
final_df_std = pd.concat([std_DataFrame, sushi_description.iloc[:,1]], axis=1)

In [26]:
final_df_std.columns=['std','desc']

In [27]:
sorted_final_df_std = final_df_std.sort_values(by=['std'], ascending = False).reset_index(drop=True)

In [28]:
print(f'Most controversial sushi with highest standard deviation: {sorted_final_df_std.iloc[0,1]}')

Most controversial sushi with highest standard deviation: awabi (abalone)


### Part 2: Common-sense solutions

In [29]:
# read in price data
sushi_info = pd.read_csv('sushi_info.csv', names=['Name', 'Category Code', 'Price'])

sushi_prices = np.asarray(sushi_info['Price'])

In [30]:
sushi_info.head()

Name  Category Code  Price
0     ebi              6  14.71
1   anago              3  15.94
2  maguro              1  15.00
3     ika              5  12.12
4     uni              8  26.30

In [31]:
test_S = set([i for i in range(1,6)])
S = np.array(list(test_S)) - 1
sushi_utilities[0, S]

array([2.58738227, 1.7350962 , 2.8057844 , 2.80849708, 2.05149979])

In [32]:
sushi_utilities

array([[2.58738227, 1.7350962 , 2.8057844 , ..., 1.36101624, 1.6240616 ,
        1.54830768],
       [1.7297663 , 1.4708043 , 1.46830921, ..., 0.27596015, 0.42032138,
        0.30896378],
       [3.34476731, 3.30225465, 3.84613956, ..., 1.43976384, 1.68563883,
        1.73443892],
       ...,
       [3.36391552, 2.90684874, 3.3925252 , ..., 3.122866  , 2.31925383,
        2.4390661 ],
       [2.85628107, 2.22074824, 2.64534802, ..., 1.08939582, 1.21020218,
        1.35564913],
       [3.91464174, 3.35614098, 3.22951918, ..., 3.23661939, 3.21807821,
        3.10566456]])

In [33]:
test_S

{1, 2, 3, 4, 5}

In [34]:
def revenue_function(sushi_utilities, sushi_prices, S):
    # computes per customer revenue of some assortment S
    # sushi_utils = k x n matrix of sushi utilities (k = # of customers, n = # of sushis)
    # sushi_prices = n x 1 vector of sushi prices
    # S = a set of sushis offered
    
    # define no-purchase utility
    no_purch_util = 3
    # variable that will store total revenue
    total_rev = 0
    # number of customers
    num_cust = len(sushi_utilities)
    # list of customers
    customers = [i for i in range(num_cust)]
    # convert assortment to numpy array so we can index with it, adjust for Python indexing
    S = np.array(list(S)) - 1
    
    # for each customer...
    for cust in customers:
        
        # extract utilities for this customer
        this_cust_utils = sushi_utilities[cust, S]
        # if highest utility is greater than the no-purchase option...
        if np.max(this_cust_utils) > no_purch_util:
            
            # extract index of the highest utility (i.e. their preferred sushi)
            sushi_pref = np.argmax(this_cust_utils)
            # extract price
            price = sushi_prices[S[sushi_pref]]
            # track total revenue
            total_rev += price
            
    # adjust total revenue for number of customers (i.e. find per customer revenue)
    revenue = total_rev / num_cust
    
    return revenue

# check function
test_S = set([i for i in range(1,6)])
print(revenue_function(sushi_utilities, sushi_prices, test_S))

14.239620000000011


In [37]:
test_S = set([i for i in range(1,6)])

In [39]:
sushi_utilities[0, np.array(list(test_S)) - 1]

array([2.58738227, 1.7350962 , 2.8057844 , 2.80849708, 2.05149979])

#### a)

In [35]:
# offer all sushis
all_S = set([i+1 for i in range(len(sushi_utilities[0]))])
# calculate revenue
print(f'Expected Revenue: {per_cust_rev(sushi_utilities, sushi_prices, all_S)}')

NameError: name 'per_cust_rev' is not defined

#### b)

In [ ]:
# offer only the 10 highest revenue sushis
top_10_rev_S = np.flip(np.argsort(sushi_prices))[:10] + 1
print(top_10_rev_S)

S = [sushi-1 for sushi in top_10_rev_S]
# subset dataframe
sushi_info = sushi_info.loc[S]
print(sushi_info['Name'])

# calculate revenue
print(f'Expected Revenue: {per_cust_rev(sushi_utilities, sushi_prices, set(top_10_rev_S))}')

### c)

In [ ]:
# set to store highest utilities for each customer
pref_utils_S = set()

# for each customer
for cust in [i for i in range(500)]:
    
    # get utilities for this customer
    this_cust = sushi_utilities[cust]
    # compute sushi of max utility
    sushi_max_util = np.argmax(this_cust) + 1
    # add this sushi to set
    pref_utils_S.add(sushi_max_util)
    
print(f'Expected Revenue: {per_cust_rev(sushi_utilities, sushi_prices, pref_utils_S)}')

We notice that this value is the same as that observed when all sushis are offered.

#### d)

Refer answer sheet

### e)

Refer answer sheet

### Part 3: An integer optimization model

#### a)

Refer to answer sheet

#### b)

In [42]:
sushi_utils.shape

(500, 100)

In [43]:
sushi_utils

array([[2.58738227, 1.7350962 , 2.8057844 , ..., 1.36101624, 1.6240616 ,
        1.54830768],
       [1.7297663 , 1.4708043 , 1.46830921, ..., 0.27596015, 0.42032138,
        0.30896378],
       [3.34476731, 3.30225465, 3.84613956, ..., 1.43976384, 1.68563883,
        1.73443892],
       ...,
       [3.36391552, 2.90684874, 3.3925252 , ..., 3.122866  , 2.31925383,
        2.4390661 ],
       [2.85628107, 2.22074824, 2.64534802, ..., 1.08939582, 1.21020218,
        1.35564913],
       [3.91464174, 3.35614098, 3.22951918, ..., 3.23661939, 3.21807821,
        3.10566456]])

In [41]:
# read in sushi utilities
sushi_utils = pd.read_csv('sushi_utilities_mat.csv',
                          names=[i for i in range(100)])
# convert to numpy array
sushi_utils = np.asarray(sushi_utils)

# initialize no-purchase utility column
no_purch_col = np.array([3 for i in range(500)]).reshape(500,1)
# add no-purchase column to utilities matrix
sushi_utils_np = np.hstack((sushi_utils, no_purch_col))
# check first 5 vals of no-purchase column
print(sushi_utils_np[:5,100])
# check shape
print(sushi_utils_np.shape)

[3. 3. 3. 3. 3.]
(500, 101)


In [ ]:
from gurobipy import *

In [ ]:
# initialize model
m_relaxed = Model()

# define dimension variabes
n_sushis = 100
n_cust = 500

# create decision variables, don't enforce them to be binary since this is the relaxation
x = m_relaxed.addVars(n_sushis, ub=1)
y = m_relaxed.addVars(n_cust, n_sushis+1, ub=1)

# add the constraints for each customer
for k in range(n_cust):
    
   
    m_relaxed.addConstr(sum(y[k,j] for j in range(n_sushis+1)) == 1)
    m_relaxed.addConstr(quicksum(sushi_utils_np[k,j] * y[k,j] for j in range(n_sushis+1)) >= sushi_utils_np[k,n_sushis])
    
    # loop through all sushis
    for i in range(n_sushis):
        
        m_relaxed.addConstr(y[k,i] <= x[i])
        m_relaxed.addConstr(quicksum(sushi_utils_np[k,j] * y[k,j] for j in range(n_sushis+1)) >= sushi_utils_np[k,i] * x[i] + sushi_utils_np[k,n_sushis] * (1 - x[i]))

# create objective function
m_relaxed.setObjective(quicksum((1 / n_cust) * sushi_prices[i] * y[k,i] for k in range(n_cust) for i in range(n_sushis)), GRB.MAXIMIZE)

# update the model
m_relaxed.update()
# solve the model
m_relaxed.optimize()

In [ ]:
# display the objective value
print(f'Optimal objective: ${m_relaxed.objval:.2f}')

#### c)

Refer to answer sheet

#### d)

In [ ]:
# initialize model
m = Model()

# define dimension variabes
n_sushis = 100
n_cust = 500

# create decision variables
x = m.addVars(n_sushis, vtype=GRB.BINARY)
y = m.addVars(n_cust, n_sushis+1, vtype=GRB.BINARY)

# add the constraints for each customer
for k in range(n_cust):
    
    # every customer makes exactly one choice
    m.addConstr(sum(y[k,j] for j in range(n_sushis+1)) == 1)
    # utility of any choice is at least the no-purchase utility
    m.addConstr(quicksum(sushi_utils_np[k,j] * y[k,j] for j in range(n_sushis+1)) >= sushi_utils_np[k,n_sushis])
    
    # loop through all sushis
    for i in range(n_sushis):
        
        # choose only from products that are in the assortment
        m.addConstr(y[k,i] <= x[i])
        # the utility of any choice is at least the utility of any included sushis
        m.addConstr(quicksum(sushi_utils_np[k,j] * y[k,j] for j in range(n_sushis+1)) >= sushi_utils_np[k,i] * x[i] + sushi_utils_np[k,n_sushis] * (1 - x[i]))

# create objective function
m.setObjective(quicksum((1 / n_cust) * sushi_prices[i] * y[k,i] for k in range(n_cust) for i in range(n_sushis)), GRB.MAXIMIZE)

# update the model
m.update()
# solve the model
m.optimize()

In [ ]:
# display the objective value
print(f'Optimal objective: ${m.objval:.2f}')

#### e)

In [ ]:
sushi_info = pd.read_csv('sushi_info.csv', names=['Name', 'Category Code', 'Price'])

In [ ]:
# extract the optimal assortment of sushis (add 1 to adjust for Python indexing)
optimal_S = [i+1 for i in range(n_sushis) if x[i].x > 0.5]
print(f'Optimal assortment: {optimal_S}')

print(per_cust_rev(sushi_utils, sushi_prices, set(optimal_S)))

In [ ]:
optimal_S_adj

In [ ]:
# get optimal assortment in terms of sushi names

optimal_S_adj = [sushi-1 for sushi in optimal_S]

sushi_info = sushi_info.iloc[optimal_S_adj]
print(sushi_info['Name'])


## 2 Hospital Staffing

In [ ]:
nurse_data = pd.read_csv('nurse.csv')

In [ ]:
nurse_data.head()

#### a)

In [ ]:
ED_cases = 12
regular_nurses = 18

#Ideally, 12 nurses would be enough to treat 12 ED_cases. So, staffing cost:

staffing_cost = regular_nurses*2160
print(f'staffing cost: {staffing_cost}')

#### b)

In [ ]:
ED_cases = 8
regular_nurses = 5
agency_nurses = ED_cases - regular_nurses

staffing_cost = regular_nurses*2160 + agency_nurses*5400
print(f'staffing cost: {staffing_cost}')

#### c, d)

Refer to answer sheet

### Part 2: Solving the Basic Newsvendor Model

In [ ]:
# read in data
nurse = pd.read_csv('nurse.csv')
# split into first 200 (train) and last 100 (test) days
train = nurse[nurse['Day'] <= 200]
test = nurse[nurse['Day'] > 200]
# split into X and y variables
X_train = train.drop(columns=['DailyED', 'Day'])
X_test = test.drop(columns=['DailyED', 'Day'])
y_train = train['DailyED']
y_test = test['DailyED']

#### a)

In [ ]:
##From part A,

co = 2160
cu = 5400 - co

quantile = cu / (cu + co)
print(f'Quantile: {quantile}')

#### b)

In [ ]:
optimal_level = round(np.quantile(y_train, quantile))
print(f'optimal_level: {optimal_level}')

#### c)

In [ ]:
# find average cost of this staffing level based on training set
train_ordinary_cost = cu * np.maximum(y_train - optimal_level, 0) + co * np.maximum(optimal_level - y_train, 0) + co * y_train
avg_train_ordinary_cost = train_ordinary_cost.mean(axis = 0)
print(f'Average cost of this staffing level based on training set: {avg_train_ordinary_cost}')

#### d)

In [ ]:
# find average cost of this staffing level based on test set
test_ordinary_cost = cu * np.maximum(y_test - optimal_level, 0) + co * np.maximum(optimal_level - y_test, 0) + co * y_test
avg_test_ordinary_cost = test_ordinary_cost.mean(axis = 0)
print(f'Average cost of this staffing level based on test set: {avg_test_ordinary_cost}')

### Part 3: Solving the Contextual Newsvendor Model

In [ ]:
# Load the tree module
import sklearn.tree as tree

In [ ]:
# Estimate the regression tree model
oj_tree = tree.DecisionTreeRegressor(max_depth = 2)
oj_tree = oj_tree.fit(X_train,y_train)

# Inspect the oj_tree object
oj_tree

#### a)

In [ ]:
conda install python-graphviz

In [ ]:
import graphviz 
from sklearn.tree import export_graphviz
tree_viz = export_graphviz(oj_tree, out_file=None,
                                feature_names=X_train.columns, impurity = False, 
                                   rounded=True,  
                                  special_characters=True) 
graph = graphviz.Source(tree_viz) 
graph.render("Nurse Staffing") 
graph

The tree splits on the variables:
<br>Root node: TotalPriorSurgeries ≤ 21.571
<br>Level 2 Decision node left: TotalPriorSurgeries ≤ 16.429
<br>Level 2 Decision node right: DailyEDLag2 ≤ 10.5

#### b)

In [ ]:
leaf_mapping = oj_tree.apply(X_train)
leaves = [i for i in range(oj_tree.tree_.node_count) if oj_tree.tree_.children_left[i] == -1 ]
# print(leaves)

leaf_to_quantile = np.zeros( oj_tree.tree_.node_count )

## using the quantile calculated from above
for ell in leaves:
    ind = leaf_mapping == ell 
    y_ell = y_train[ind]
    leaf_to_quantile[ell] = round(np.quantile(y_ell, quantile))
    
leaf_to_quantile

#### c)

In [ ]:
train_leaves = oj_tree.apply(X_train)
train_decisions = leaf_to_quantile[train_leaves]

# calculate cost
train_set_cost = cu * np.maximum(y_train - train_decisions, 0) + co * np.maximum(train_decisions - y_train, 0) + co * y_train

# take average
avg_train_set_cost = train_set_cost.mean(axis = 0)
print(avg_train_set_cost)

#### d)

In [ ]:
test_leaves = oj_tree.apply(X_test)
test_decisions = leaf_to_quantile[test_leaves]

# calculate cost
test_set_cost = cu * np.maximum(y_test - test_decisions, 0) + co * np.maximum(test_decisions - y_test, 0) + co * y_test

# take average
avg_test_set_cost = test_set_cost.mean(axis = 0)
print(avg_test_set_cost)